repository: dynamsoft-docs/document-normalizer-docs-server
repositoryUrl: https://github.com/dynamsoft-docs/document-normalizer-docs-server/blob/v2
docFullPath: https://www.dynamsoft.com/document-normalizer/docs/v2/server/
firstLevelUrl: /document-normalizer/docs/v2/server
docHomePage: /document-normalizer/docs/v2/core/introduction/
needSearchIndex: true
searchNeedFilter: true

ddn_cpp: /document-normalizer/docs/v2/server/programming/cplusplus/
ddn_cpp_api: /document-normalizer/docs/v2/server/programming/cplusplus/api-reference/
ddn_dotnet: /document-normalizer/docs/v2/server/programming/dotnet/
ddn_dotnet_api: /document-normalizer/docs/v2/server/programming/dotnet/api-reference/
ddn_python: /document-normalizer/docs/v2/server/programming/python/
ddn_python_api: /document-normalizer/docs/v2/server/programming/python/api-reference/


dcvb_parameters_reference: /capture-vision/docs/v2/core/parameters/reference/

dcvb_cpp_api: /capture-vision/docs/v2/server/programming/cplusplus/api-reference/
dcvb_dotnet_api: /capture-vision/docs/v2/server/programming/dotnet/api-reference/
dcvb_python_api: /capture-vision/docs/v2/server/programming/python/api-reference/
dcvb_introduction: /capture-vision/docs/v2/core/introduction/
dcvb_enumerations: /capture-vision/docs/v2/core/enums/

useVersionTree: false 
isDCV: true
useJSVersionV3: true

assets: /document-normalizer/docs/v2/server/assets/
edit_icon: /document-normalizer/docs/v2/server/assets/img-icon/edit-icon.png
smile_icon: /document-normalizer/docs/v2/server/assets/img-icon/icon-smile.png
sad_icon: /document-normalizer/docs/v2/server/assets/img-icon/icon-sad.png

baseurl: "/document-normalizer/docs/v2/server"


plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope: 
      path: "programming/cplusplus" 
    values: 
      docRootName: "Document Normalizer C++" 
      docHomePage: "/document-normalizer/docs/v2/server/programming/cplusplus/"
  - scope: 
      path: "programming/dotnet" 
    values: 
      docRootName: "Document Normalizer .NET Edition" 
      docHomePage: "/document-normalizer/docs/v2/server/programming/dotnet/"
  - scope: 
      path: "programming/python" 
    values: 
      docRootName: "Document Normalizer Python Edition" 
      docHomePage: "/document-normalizer/docs/v2/server/programming/python/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
